flowchart LR
  N1["Complete Eighth Grade"]
  N2["Submit Eighth-Grade Transcript"]
  N3["Evaluation"]
  N4["Ninth-Grade Eligibility"]
  N5["Ninth-Grade Enrollment"]
  N1 --> N2
  N2 --> N3
  N3 --> N4
  N4 --> N5
