flowchart LR
  N1["Student"]
  N2["SuiteDash Help Desk"]
  N3["Ticket"]
  N4["Applicable Department"]
  N5["Human Support"]
  N6["Resolution"]
  N1 --> N2
  N2 --> N3
  N3 --> N4
  N4 --> N5
  N5 --> N6
