flowchart LR
  N1["Review Completed Courses"]
  N2["Evaluate Earned Credits"]
  N3["Determine Applicable Grade Level"]
  N4["Identify Remaining High School Requirements"]
  N5["Determine Concurrent College Course Eligibility"]
  N6["Develop Student Academic Pathway."]
  N1 --> N2
  N2 --> N3
  N3 --> N4
  N4 --> N5
  N5 --> N6
