flowchart LR
  N1["Select Minor"]
  N2["Review Minor Prerequisites"]
  N3["Evaluate Completed Coursework"]
  N4["Complete Outstanding Prerequisites"]
  N5["Minor Program Admission."]
  N1 --> N2
  N2 --> N3
  N3 --> N4
  N4 --> N5
