flowchart LR
  N1["General Education Evaluation"]
  N2["School Core Evaluation"]
  N3["Identify Completed Requirements"]
  N4["Identify Outstanding Requirements"]
  N5["Complete Outstanding Requirements, If Applicable"]
  N6["Year 3 Admissions Eligibility"]
  N7["Application and Admission Review."]
  N1 --> N2
  N2 --> N3
  N3 --> N4
  N4 --> N5
  N5 --> N6
  N6 --> N7
