flowchart LR
  N1["Review Eligibility"]
  N2["Submit Records"]
  N3["$125 Transfer Credit Evaluation"]
  N4["$125 Processing Upon Applicable Admission"]
  N5["Credit Determination"]
  N6["Admission"]
  N7["Enrollment"]
  N8["Transfer Kit"]
  N9["Orientation"]
  N10["Active Student"]
  N1 --> N2
  N2 --> N3
  N3 --> N4
  N4 --> N5
  N5 --> N6
  N6 --> N7
  N7 --> N8
  N8 --> N9
  N9 --> N10
