%%{init: {"theme":"base","themeVariables":{"primaryColor":"#111111","primaryTextColor":"#FFFFFF","primaryBorderColor":"#CC0000","lineColor":"#CC0000","secondaryColor":"#CC0000","tertiaryColor":"#111111"}}}%%
flowchart TD
    N0["RIAH PATHWAY"] --> N1
    N1["ACADEMIC ECOSYSTEM"] --> N2
    N2["SECONDARY SCHOOL: High School Diploma; GED/HSE Preparation"] --> N3
    N3["POSTSECONDARY PATHWAYS: General Education; School Core; Minor; Bachelor’s Major; Master’s; MBA; JD; Non-JD Law Pathways"]
