flowchart LR
  N1["Placement: Automated student sorting"]
  N2["monthly cohort"]
  N3["school community"]
  N4["cohort community"]
  N5["peer/buddy connection."]
  N1 --> N2
  N2 --> N3
  N3 --> N4
  N4 --> N5
