flowchart LR
  N1["Evaluate General Education"]
  N2["Evaluate School Core"]
  N3["Identify Outstanding Requirements"]
  N4["Complete Requirements"]
  N5["Year 3 Eligibility"]
  N6["Review"]
  N1 --> N2
  N2 --> N3
  N3 --> N4
  N4 --> N5
  N5 --> N6
