flowchart LR
  N1["Submit Bachelor's Degree and Academic Records"]
  N2["Evaluate Degree Applicability or Equivalency"]
  N3["Evaluate Program Prerequisites"]
  N4["Complete Missing Prerequisites, If Applicable"]
  N5["Graduate Admissions Eligibility"]
  N6["Application and Admission Review."]
  N1 --> N2
  N2 --> N3
  N3 --> N4
  N4 --> N5
  N5 --> N6
